### ISSUE TITLE
What are the valid values for the Zoom level? 

### ISSUE THREAD

**Issue by timmyreilly** [BretStateham/FlySimExpress#10]
We were having some issues with the zoom level on the UWP displaying the metadata, altitude and name, over the planes.

**Comment by ms-vincent** [comment]
I set the zoom level to 200-300 (default is 80) but it appeared as though that didn't have an influence on how the metadata showed.

**Comment by BretStateham** [comment]
I set it to 1100 or so.  It matches the number shown in the top right corner of the map as you zoom in and out.  Basically zoom out as far as you would like to be able to see the labels on the dots and set the zoom level at or above that number. 

I have changed it in the repo to 1100 as the default.
